export const services = [
  {
    id: 1,
    slug: "web-development",
    title: "Web Development",
    icon: "Globe",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format,compress&fit=crop&w=1600&q=100",
    description: "Custom websites, landing pages, full-stack web apps.",
    details: "We build world-class web experiences using the latest technologies. From high-converting landing pages to complex enterprise web applications, we focus on performance, SEO, and scalability.",
    deliverables: ["React/Next.js", "REST APIs", "Node.js backend", "MongoDB", "responsive design", "SEO-ready", "performance optimized"],
    tags: ["React", "Node.js", "MongoDB", "Tailwind"],
    price: "₹15,000",
  },
  {
    id: 2,
    slug: "app-development",
    title: "App Development",
    icon: "Smartphone",
    image: "https://images.unsplash.com/photo-1551650975-87deedd944c3?auto=format,compress&fit=crop&w=1600&q=100",
    description: "Cross-platform mobile apps for iOS and Android.",
    details: "Your vision on every screen. We specialize in React Native and Flutter to deliver smooth, native-like mobile experiences that work perfectly on both iOS and Android platforms.",
    deliverables: ["React Native / Flutter", "push notifications", "auth", "app store deployment", "offline support"],
    tags: ["React Native", "Flutter", "Firebase", "REST API"],
    price: "₹25,000",
  },
  {
    id: 3,
    slug: "brand-design",
    title: "Brand & Design",
    icon: "Palette",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format,compress&fit=crop&w=1600&q=100",
    description: "Visual identity that makes people stop scrolling.",
    details: "Design that demands attention. We create cohesive brand identities and UI/UX designs that not only look stunning but are strategically crafted to convert users into loyal customers.",
    deliverables: ["Logo design", "brand guidelines", "UI/UX design in Figma", "design systems", "social media kits"],
    tags: ["Figma", "Illustrator", "Framer"],
    price: "₹10,000",
  },
  {
    id: 4,
    slug: "automation-ai",
    title: "Automation & AI",
    icon: "Bot",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format,compress&fit=crop&w=1600&q=100",
    description: "Automate repetitive workflows. Save 10+ hours/week.",
    details: "Work smarter, not harder. We leverage cutting-edge AI and automation tools to streamline your business processes, saving you time and money while increasing accuracy.",
    deliverables: ["Zapier/Make automations", "AI chatbots", "CRM integrations", "email sequences", "WhatsApp automation", "API connections"],
    tags: ["Make", "Zapier", "OpenAI", "Webhook"],
    price: "₹8,000",
  },
  {
    id: 5,
    slug: "deployment-devops",
    title: "Deployment & DevOps",
    icon: "Rocket",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format,compress&fit=crop&w=1600&q=100",
    description: "Launch fast. Stay live. Scale without stress.",
    details: "Zero-downtime deployments and rock-solid infrastructure. We handle everything from server setup to CI/CD pipelines, ensuring your app is always fast, secure, and available.",
    deliverables: ["VPS setup", "CI/CD pipelines", "Docker", "Nginx config", "domain + SSL", "monitoring", "uptime alerts"],
    tags: ["AWS", "Vercel", "Docker", "Nginx"],
    price: "₹5,000",
  },
  {
    id: 6,
    slug: "full-website-package",
    title: "Full Website Package",
    icon: "Briefcase",
    image: "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format,compress&fit=crop&w=1600&q=100",
    description: "Everything from brand to launch in one package.",
    details: "The ultimate solution for new businesses. We take you from a blank page to a fully functional, branded website in just 7 days. This includes design, development, and deployment.",
    deliverables: ["Design + Dev + Deploy + SEO + Support", "7-day delivery", "code ownership certificate"],
    tags: ["Full Stack", "Figma", "SEO", "Launch"],
    price: "₹35,000",
  },
  {
    id: 7,
    slug: "api-integrations",
    title: "API Integrations",
    icon: "Link",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format,compress&fit=crop&w=1600&q=100",
    description: "Connect your tools. Build smart workflows.",
    details: "Seamlessly connect your digital ecosystem. We integrate payment gateways, CRMs, and third-party tools to ensure your data flows smoothly across all your platforms.",
    deliverables: ["Payment gateways (Razorpay/Stripe)", "CRM", "email marketing", "analytics", "custom API development"],
    tags: ["Razorpay", "Stripe", "REST", "GraphQL"],
    price: "₹12,000",
  },
  {
    id: 8,
    slug: "seo-performance",
    title: "SEO & Performance",
    icon: "TrendingUp",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format,compress&fit=crop&w=1600&q=100",
    description: "Rank higher. Load faster. Convert better.",
    details: "Speed is a feature. We optimize your site for Google's Core Web Vitals and implement advanced SEO strategies to ensure you rank at the top and stay there.",
    deliverables: ["On-page SEO", "Core Web Vitals fixes", "image optimization", "structured data", "performance audits"],
    tags: ["Lighthouse", "GA4", "Schema", "PageSpeed"],
    price: "₹7,000",
  }
];
