export const project = {
  name: "E-Commerce Platform Redesign",
  client: "Ramesh Patel",
  company: "PatelMart Pvt. Ltd.",
  status: "In Progress",
  startDate: "March 10, 2025",
  deadline: "July 30, 2025",
  progress: 68,
  domain: "www.patelmart.com",
  registrar: "GoDaddy",
  domainExpiry: "March 10, 2027",
  sslStatus: "Active",
  overview:
    "Complete redesign and development of PatelMart's e-commerce platform including new UI, payment gateway integration, inventory management system, and mobile-responsive frontend.",
  teamSize: 6,
  budget: 500000,
  spent: 320000,
  daysLeft: 47,
}

export const teamMembers = [
  {
    id: 1,
    name: "Arjun Shah",
    role: "Lead Developer",
    initials: "AS",
    color: "bg-indigo-500",
    online: true,
    skills: ["React", "Node.js", "AWS"],
  },
  {
    id: 2,
    name: "Priya Mehta",
    role: "UI/UX Designer",
    initials: "PM",
    color: "bg-cyan-500",
    online: true,
    skills: ["Figma", "UI/UX", "Motion"],
  },
  {
    id: 3,
    name: "Rahul Verma",
    role: "Backend Engineer",
    initials: "RV",
    color: "bg-emerald-500",
    online: false,
    skills: ["Python", "PostgreSQL", "Redis"],
  },
  {
    id: 4,
    name: "Sneha Kapoor",
    role: "QA Engineer",
    initials: "SK",
    color: "bg-amber-500",
    online: true,
    skills: ["Testing", "Cypress", "Jest"],
  },
  {
    id: 5,
    name: "Dev Patel",
    role: "DevOps Engineer",
    initials: "DP",
    color: "bg-rose-500",
    online: false,
    skills: ["Docker", "K8s", "CI/CD"],
  },
  {
    id: 6,
    name: "Anjali Singh",
    role: "Project Manager",
    initials: "AS",
    color: "bg-violet-500",
    online: true,
    skills: ["Agile", "Jira", "Strategy"],
  },
]

export const milestones = [
  {
    id: 1,
    phase: "Discovery",
    status: "completed",
    dateRange: "Mar 10 — Mar 24",
    assignee: "Anjali Singh",
    progress: 100,
  },
  {
    id: 2,
    phase: "Design",
    status: "completed",
    dateRange: "Mar 25 — Apr 14",
    assignee: "Priya Mehta",
    progress: 100,
  },
  {
    id: 3,
    phase: "Development",
    status: "in-progress",
    dateRange: "Apr 15 — Jun 30",
    assignee: "Arjun Shah",
    progress: 60,
  },
  {
    id: 4,
    phase: "Testing",
    status: "upcoming",
    dateRange: "Jul 1 — Jul 20",
    assignee: "Sneha Kapoor",
    progress: 0,
  },
  {
    id: 5,
    phase: "Launch",
    status: "upcoming",
    dateRange: "Jul 21 — Jul 30",
    assignee: "Anjali Singh",
    progress: 0,
  },
]

export const notifications = [
  {
    id: 1,
    type: "payment",
    icon: "check",
    message: "Invoice #004 has been paid — ₹45,000",
    time: "2 hours ago",
    read: false,
  },
  {
    id: 2,
    type: "dev",
    icon: "rocket",
    message: "Development phase started",
    time: "1 day ago",
    read: false,
  },
  {
    id: 3,
    type: "message",
    icon: "message",
    message: "New message from Nexoraa team",
    time: "2 days ago",
    read: false,
  },
  {
    id: 4,
    type: "files",
    icon: "paperclip",
    message: "3 new files added to Asset Vault",
    time: "3 days ago",
    read: true,
  },
  {
    id: 5,
    type: "update",
    icon: "info",
    message: "Milestone 2 completed ahead of schedule",
    time: "5 days ago",
    read: true,
  },
]

export const invoices = [
  {
    id: "INV-001",
    date: "Mar 10, 2025",
    description: "Project Advance Payment",
    amount: 100000,
    status: "paid",
  },
  {
    id: "INV-002",
    date: "Apr 5, 2025",
    description: "Advance Payment",
    amount: 100000,
    status: "paid",
  },
  {
    id: "INV-003",
    date: "May 10, 2025",
    description: "Milestone 1 — Design Complete",
    amount: 120000,
    status: "paid",
  },
  {
    id: "INV-004",
    date: "Jun 1, 2025",
    description: "Milestone 2 — Dev Phase 1",
    amount: 100000,
    status: "paid",
  },
  {
    id: "INV-005",
    date: "Jul 15, 2025",
    description: "Final Payment — Launch",
    amount: 180000,
    status: "pending",
  },
]

export const paymentTimeline = [
  {
    date: "Apr 5",
    label: "Advance Payment",
    amount: 100000,
    status: "paid",
  },
  {
    date: "May 10",
    label: "Milestone 1",
    amount: 120000,
    status: "paid",
  },
  {
    date: "Jun 1",
    label: "Milestone 2",
    amount: 100000,
    status: "paid",
  },
  {
    date: "Jul 15",
    label: "Final Payment",
    amount: 180000,
    status: "pending",
  },
]

export const assetFiles = [
  {
    id: 1,
    name: "Brand_Guidelines_v2.pdf",
    type: "pdf",
    size: "4.2 MB",
    folder: "Design Assets",
    date: "May 15, 2025",
  },
  {
    id: 2,
    name: "Homepage_Wireframes.fig",
    type: "fig",
    size: "12.8 MB",
    folder: "Design Assets",
    date: "Apr 20, 2025",
  },
  {
    id: 3,
    name: "Logo_Package.zip",
    type: "zip",
    size: "8.1 MB",
    folder: "Branding",
    date: "Mar 28, 2025",
  },
  {
    id: 4,
    name: "Product_Photos.zip",
    type: "zip",
    size: "156 MB",
    folder: "Content",
    date: "May 1, 2025",
  },
  {
    id: 5,
    name: "App_Demo.mp4",
    type: "mp4",
    size: "38.4 MB",
    folder: "Videos",
    date: "Jun 1, 2025",
  },
  {
    id: 6,
    name: "Homepage_Preview.png",
    type: "png",
    size: "2.1 MB",
    folder: "Design Assets",
    date: "May 22, 2025",
  },
  {
    id: 7,
    name: "API_Documentation.pdf",
    type: "pdf",
    size: "1.8 MB",
    folder: "Technical",
    date: "May 30, 2025",
  },
  {
    id: 8,
    name: "Database_Schema.png",
    type: "png",
    size: "780 KB",
    folder: "Technical",
    date: "Apr 10, 2025",
  },
]

export const folders = [
  { id: 1, name: "Design Assets", count: 14, color: "text-blue-400" },
  { id: 2, name: "Branding", count: 6, color: "text-purple-400" },
  { id: 3, name: "Content", count: 23, color: "text-amber-400" },
  { id: 4, name: "Technical", count: 9, color: "text-emerald-400" },
  { id: 5, name: "Videos", count: 3, color: "text-rose-400" },
]

export const channels = [
  { id: 1, name: "general", unread: 2 },
  { id: 2, name: "design-feedback", unread: 0 },
  { id: 3, name: "dev-updates", unread: 5 },
]

export const messages = {
  1: [
    {
      id: 1,
      sender: "Arjun Shah",
      initials: "AS",
      color: "bg-indigo-500",
      content:
        "Good morning! Quick update — the homepage animations are now complete and pushed to staging.",
      time: "9:15 AM",
      type: "user",
      reactions: [{ emoji: "👍", count: 2 }, { emoji: "🚀", count: 1 }],
    },
    {
      id: 2,
      sender: "Priya Mehta",
      initials: "PM",
      color: "bg-cyan-500",
      content:
        "Looks amazing! The micro-interactions on the product cards are exactly what we discussed.",
      time: "9:22 AM",
      type: "user",
      reactions: [],
    },
    {
      id: 3,
      sender: "system",
      initials: "",
      color: "",
      content: "Development phase started",
      time: "9:30 AM",
      type: "system",
      reactions: [],
    },
    {
      id: 4,
      sender: "Anjali Singh",
      initials: "AS",
      color: "bg-violet-500",
      content:
        "Ramesh, the staging link is ready for your review: https://staging.patelmart.com — Please share any feedback by Friday!",
      time: "10:05 AM",
      type: "user",
      reactions: [{ emoji: "✅", count: 1 }],
    },
    {
      id: 5,
      sender: "Ramesh Patel",
      initials: "RP",
      color: "bg-amber-500",
      content:
        "Excellent work team! I reviewed the staging. The checkout flow feels very smooth. Just one question — can we add a wishlist feature?",
      time: "11:30 AM",
      type: "user",
      reactions: [{ emoji: "💬", count: 3 }],
    },
  ],
  2: [
    {
      id: 1,
      sender: "Priya Mehta",
      initials: "PM",
      color: "bg-cyan-500",
      content: "Sharing the updated color palette for the product pages. Please review the contrast ratios.",
      time: "Yesterday",
      type: "user",
      reactions: [],
    },
    {
      id: 2,
      sender: "Arjun Shah",
      initials: "AS",
      color: "bg-indigo-500",
      content: "The new palette looks great. The indigo/amber combination works well for the CTA buttons.",
      time: "Yesterday",
      type: "user",
      reactions: [{ emoji: "👍", count: 1 }],
    },
  ],
  3: [
    {
      id: 1,
      sender: "Arjun Shah",
      initials: "AS",
      color: "bg-indigo-500",
      content: "Backend API for products is now live. All endpoints documented in the vault.",
      time: "2 days ago",
      type: "user",
      reactions: [],
    },
    {
      id: 2,
      sender: "Rahul Verma",
      initials: "RV",
      color: "bg-emerald-500",
      content: "Payment gateway integration is 80% complete. Testing with sandbox credentials this week.",
      time: "1 day ago",
      type: "user",
      reactions: [{ emoji: "🚀", count: 2 }],
    },
    {
      id: 3,
      sender: "Dev Patel",
      initials: "DP",
      color: "bg-rose-500",
      content: "CI/CD pipeline updated. All PRs now auto-deploy to feature environments.",
      time: "Today",
      type: "user",
      reactions: [],
    },
  ],
}
